title: Hamish
description: Management Consultant
author: Hamish

# Build settings
theme: minima

# Minima settings
minima:
  skin: classic
  
header_pages:
  - about.md
  - archive.md

# URL settings  
url: https://hamishfrostlyon.github.io
baseurl: ""
