title: Do Good Works
tagline: 
description: Management consultant writing about strategy, operations, and digital transformation
url: https://hamishfrostlyon.github.io
baseurl: ''

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Language settings - AUSTRALIAN
lang: en-AU
locale: en_AU
timezone: Australia/Perth

# Author
author:
  name: Hamish Lyon
  linkedin: hamishfrostlyon

# Site verification
google_site_verification: # Add your Google verification code
bing_site_verification: # Add your Bing verification code

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# SEO
keywords:
  - management consulting
  - digital transformation
  - operations strategy
  - business strategy

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Include
include:
  - _pages

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
