title: Hamish Lyon
tagline: Management Consultant
description: Management consultant writing about strategy, operations, and digital transformation
url: https://hamishfrostlyon.github.io
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Language settings - AUSTRALIAN
lang: en-AU
locale: en_AU
timezone: Australia/Perth

# Author
author:
  name: Hamish Lyon
  linkedin: hamishfrostlyon

# Site verification
google_site_verification: # Add your Google verification code
bing_site_verification: # Add your Bing verification code

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-responsive-image

# SEO
keywords:
  - management consulting
  - digital transformation
  - operations strategy
  - business strategy

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Responsive Images
responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 400
      quality: 85
    - width: 800
      quality: 85
    - width: 1200
      quality: 90
  default_quality: 85
  output_path_format: assets/images/resized/%{filename}-%{width}w.%{extension}
  save_to_source: false
  strip: true
  extra_images:
    - assets/images/historical-cost-of-computer-memory-and-storage.png

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Include
include:
  - _pages

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
